Added Eliminar ofertas and Listar ofertas
jorgegmez/manage_airlines_booking pull request #2
Opened 2021-11-21 03:11 UTC by aricastr

Crear ofertas modificado para adaptacion con los metodos

2021-11-21 03:47 UTC, aricastr commented
The multiple arrays can be replaced with an array of object for optimization

2021-11-23 15:31 UTC, jorgegmez requested changes

2021-11-23 15:31 UTC, jorgegmez commented on src/nbframework_airlines_booking/Ofertas.java
> +    int precio_array[] = new int[100];
Replace all these arrays for one array of objects

2021-11-23 15:31 UTC, jorgegmez commented on src/nbframework_airlines_booking/Ofertas.java
> +        // The following can be used to take info for the variables, however I would propose to use arrays instead to sort the info accordingly
Please remove this code is no longer need it.

2021-12-10 14:24 UTC, merged